/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.Pedido;
import Model.Pessoa;
import Model.Produto;
import Controller.PedidoDAO;
import Controller.PessoaDAO;
import Controller.ProdutoDAO;
import Controller.TipoDAO;
import Model.Tipo;
import java.awt.HeadlessException;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.Timer;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import utilitarios.AceitaNumeros;
import utilitarios.AceitaNumerosPonto;
import utilitarios.ConverteData;

/**
 *
 * @author Strong
 */
public class FormEstoque extends javax.swing.JFrame {

    private PedidoDAO pedidoDAO;
    /**
     * Creates new form caixa
     */
    double valorRecebido = 0;
    double total = 0;

    public FormEstoque() {
        initComponents();
        txtItem.setVisible(false);
        lblSituacao.setVisible(false);

        txtQtde.setDocument(new AceitaNumeros());
        txtValor.setDocument(new AceitaNumerosPonto());
        
        txtItem.setText(String.valueOf(tblProdutos.getRowCount() + 1));

        this.pedidoDAO = new PedidoDAO();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoEstoque = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        lblFuncionario = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProdutos = new javax.swing.JTable();
        btnClear = new javax.swing.JButton();
        cbFuncionario = new javax.swing.JComboBox();
        btnConcluir = new javax.swing.JButton();
        lblFornecedor = new javax.swing.JLabel();
        cbFornecedor = new javax.swing.JComboBox();
        btnFornecedor = new javax.swing.JButton();
        btnFuncionario = new javax.swing.JButton();
        pnlEstoque = new javax.swing.JPanel();
        rbEntrada = new javax.swing.JRadioButton();
        rbSaida = new javax.swing.JRadioButton();
        btnEntrada = new javax.swing.JButton();
        btnSaida = new javax.swing.JButton();
        lblData = new javax.swing.JLabel();
        lblHora = new javax.swing.JLabel();
        txtItem = new javax.swing.JTextField();
        lblSituacao = new javax.swing.JLabel();
        pnlProduto = new javax.swing.JPanel();
        lblProduto = new javax.swing.JLabel();
        cbProduto = new javax.swing.JComboBox();
        lblQtde = new javax.swing.JLabel();
        txtQtde = new javax.swing.JTextField();
        lblValor = new javax.swing.JLabel();
        txtValor = new javax.swing.JTextField();
        btnProduto = new javax.swing.JButton();
        lblDestino = new javax.swing.JLabel();
        txtDestino = new javax.swing.JTextField();
        txtTotal = new javax.swing.JTextField();
        lblTotal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(".: Controle de ESTOQUE :.");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblFuncionario.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblFuncionario.setText("Funcionário:");

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        tblProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cod.Pedido", "Data", "Tipo", "Funcionário", "Destino", "Cod. Item", "Produto", "Qtde.", "Valor Unitário"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblProdutos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProdutosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblProdutos);
        if (tblProdutos.getColumnModel().getColumnCount() > 0) {
            tblProdutos.getColumnModel().getColumn(0).setResizable(false);
            tblProdutos.getColumnModel().getColumn(1).setResizable(false);
            tblProdutos.getColumnModel().getColumn(2).setResizable(false);
            tblProdutos.getColumnModel().getColumn(3).setResizable(false);
            tblProdutos.getColumnModel().getColumn(4).setResizable(false);
            tblProdutos.getColumnModel().getColumn(5).setResizable(false);
            tblProdutos.getColumnModel().getColumn(6).setResizable(false);
            tblProdutos.getColumnModel().getColumn(7).setResizable(false);
            tblProdutos.getColumnModel().getColumn(8).setResizable(false);
        }

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Clear.png"))); // NOI18N
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnConcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ok.png"))); // NOI18N
        btnConcluir.setText("Concluir");
        btnConcluir.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnConcluir.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnConcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConcluirActionPerformed(evt);
            }
        });

        lblFornecedor.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblFornecedor.setText("Fornecedor:");

        cbFornecedor.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        btnFornecedor.setText("...");
        btnFornecedor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                btnFornecedorFocusLost(evt);
            }
        });
        btnFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFornecedorActionPerformed(evt);
            }
        });

        btnFuncionario.setText("...");
        btnFuncionario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                btnFuncionarioFocusLost(evt);
            }
        });
        btnFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFuncionarioActionPerformed(evt);
            }
        });

        pnlEstoque.setBorder(javax.swing.BorderFactory.createTitledBorder("Controle do ESTOQUE:"));

        rbEntrada.setText("Repor (Entrada)");
        rbEntrada.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbEntradaMouseClicked(evt);
            }
        });

        rbSaida.setText("Dar Baixa (Saída)");
        rbSaida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbSaidaMouseClicked(evt);
            }
        });

        btnEntrada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/box-in.png"))); // NOI18N
        btnEntrada.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEntradaMouseClicked(evt);
            }
        });
        btnEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntradaActionPerformed(evt);
            }
        });

        btnSaida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/box-out.png"))); // NOI18N
        btnSaida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaidaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlEstoqueLayout = new javax.swing.GroupLayout(pnlEstoque);
        pnlEstoque.setLayout(pnlEstoqueLayout);
        pnlEstoqueLayout.setHorizontalGroup(
            pnlEstoqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlEstoqueLayout.createSequentialGroup()
                .addGroup(pnlEstoqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbEntrada)
                    .addGroup(pnlEstoqueLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(btnEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(pnlEstoqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlEstoqueLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(rbSaida)
                        .addContainerGap(12, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlEstoqueLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSaida, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42))))
        );
        pnlEstoqueLayout.setVerticalGroup(
            pnlEstoqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEstoqueLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(pnlEstoqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbEntrada)
                    .addComponent(rbSaida))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlEstoqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSaida, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEntrada, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        lblData.setForeground(new java.awt.Color(0, 0, 204));
        lblData.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblData.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Calendar.png"))); // NOI18N
        lblData.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblData.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        lblHora.setFont(new java.awt.Font("Impact", 0, 16)); // NOI18N
        lblHora.setForeground(new java.awt.Color(0, 0, 204));
        lblHora.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblHora.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/clock.png"))); // NOI18N
        lblHora.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtItem.setEditable(false);
        txtItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtItemActionPerformed(evt);
            }
        });

        lblSituacao.setText("Em Aberto");

        pnlProduto.setBorder(javax.swing.BorderFactory.createTitledBorder("Produtos:"));

        lblProduto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblProduto.setText("Produto:");

        cbProduto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbProdutoMouseClicked(evt);
            }
        });

        lblQtde.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblQtde.setText("Qtde:");

        txtQtde.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lblValor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblValor.setText("Valor Unitário:");

        txtValor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtValor.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        btnProduto.setText("...");
        btnProduto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                btnProdutoFocusLost(evt);
            }
        });
        btnProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProdutoActionPerformed(evt);
            }
        });

        lblDestino.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblDestino.setText("Destino:");

        txtDestino.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout pnlProdutoLayout = new javax.swing.GroupLayout(pnlProduto);
        pnlProduto.setLayout(pnlProdutoLayout);
        pnlProdutoLayout.setHorizontalGroup(
            pnlProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlProdutoLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(lblProduto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
            .addGroup(pnlProdutoLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(pnlProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblQtde)
                    .addComponent(lblDestino))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlProdutoLayout.createSequentialGroup()
                        .addComponent(txtQtde, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(lblValor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        pnlProdutoLayout.setVerticalGroup(
            pnlProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProdutoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProduto)
                    .addComponent(cbProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnProduto))
                .addGap(30, 30, 30)
                .addGroup(pnlProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtQtde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblQtde)
                    .addComponent(lblValor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(pnlProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDestino))
                .addContainerGap())
        );

        lblTotal.setText("Valor Total");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblFuncionario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblFornecedor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(pnlProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtItem, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblSituacao)
                                .addGap(22, 22, 22)
                                .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnConcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(pnlEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblData, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(lblTotal)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTotal, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblHora, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFuncionario)
                    .addComponent(cbFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFuncionario)
                    .addComponent(cbFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFornecedor)
                    .addComponent(btnFornecedor))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(pnlEstoque, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnConcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblSituacao))))
                    .addComponent(pnlProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTotal))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lblData, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE))
                    .addComponent(lblHora, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pnlProduto.getAccessibleContext().setAccessibleDescription("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        btnEntrada.setEnabled(false);
        btnSaida.setEnabled(false);
        
        //Pega Data
        Date dataSistema = new Date();

        SimpleDateFormat formato = new SimpleDateFormat("EEEE, dd MMMM yyyy");
        //EEEE - mostra o dia da semana por extenso
        lblData.setText(formato.format(dataSistema));

        //Pega Hora
        Timer timer = new Timer(1000, new hora());
        timer.start();

        PessoaDAO pesDAO = new PessoaDAO();
        ArrayList<Pessoa> pes = new ArrayList<Pessoa>();
        pes = pesDAO.getFuncionario();

        for (Pessoa p : pes) {
            if (p != null) {
                cbFuncionario.addItem(p.getP_nome());
            }
        }
        cbFuncionario.setSelectedIndex(-1);
        
        PessoaDAO fornDAO = new PessoaDAO();
        ArrayList<Pessoa> forn = new ArrayList<Pessoa>();
        forn = fornDAO.getFornecedor();
            
        for (Pessoa f : forn) {
            if (f != null) {
                cbFornecedor.addItem(f.getP_nome());
            }
        }
        cbFornecedor.setSelectedIndex(-1);

        ProdutoDAO prodDAO = new ProdutoDAO();
        ArrayList<Produto> prod = new ArrayList<Produto>();
        prod = prodDAO.getProdutosByDesc();

        for (Produto p : prod) {
            if (p != null) {
                cbProduto.addItem(p.getDescProduto());
            }
        }
        cbProduto.setSelectedIndex(-1);
                
        btnConcluir.setEnabled(true);
        grupoEstoque.add(rbEntrada);
        grupoEstoque.add(rbSaida);
        //rbEntrada.setSelected(true);// inicia selecionado
        
        lblFornecedor.setVisible(true);
        btnFornecedor.setVisible(true);
        cbFornecedor.setVisible(true);
    }//GEN-LAST:event_formWindowOpened

    private void btnEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntradaActionPerformed
        // TODO add your handling code here:
        Date dataSistema = new Date();
        SimpleDateFormat data = new SimpleDateFormat("yyyy-MM-dd");
        
        try {
            String ped_cod = txtItem.getText();
            String ped_data = data.format(dataSistema);
            String ped_tipo = ""; 
                if (rbEntrada.isSelected())
                {
                    ped_tipo = "E";
                }
            String pes_id = cbFuncionario.getSelectedItem().toString();
            String ped_destino = txtDestino.getText();
            String produto = cbProduto.getSelectedItem().toString();
            String qtde = txtQtde.getText();
            String valor = txtValor.getText();

            double valorItem = 0;
            
            DecimalFormat df = new DecimalFormat("R$ "+"#,###,##0.00");
            valorItem = Double.parseDouble(qtde) * Double.parseDouble(valor);         
                        
            DefaultTableModel tabelaProdutos = (DefaultTableModel) tblProdutos.getModel();
            Object[] obj = new Object[]{
                ped_cod,
                ped_data,
                ped_tipo,
                pes_id,
                ped_destino,
                ped_cod,
                produto,
                qtde,
                valorItem,
                df.format(valorItem)
            };
            
            
            //df.format(total);
            //txtTPagar.setText(String.valueOf(total));
            tabelaProdutos.addRow(obj);
            //txtItem.setText(String.valueOf(tblProdutos.getRowCount() + 1));
            somarColunaTotal();
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "É necessário preencher corretamente todos\n os campos do Produto !\nErro: " + e.getMessage());
        }
    }//GEN-LAST:event_btnEntradaActionPerformed

    private void btnSaidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaidaActionPerformed
        // TODO add your handling code here:
        int linhaSelecionada = tblProdutos.getSelectedRow();
        DecimalFormat df = new DecimalFormat("#,###.00");

        if (linhaSelecionada >= 0) {
            DefaultTableModel tabelaProdutos = (DefaultTableModel) tblProdutos.getModel();
            tabelaProdutos.removeRow(linhaSelecionada);

            cbProduto.setSelectedIndex(-1);
            txtQtde.setText("");
            txtValor.setText("");
        } else {
            JOptionPane.showMessageDialog(null, "Selecione um produto para remover da lista !");
        }
    }//GEN-LAST:event_btnSaidaActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        int dialogButton = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja limpar todos os campos ?", "Warning", 0);// 0 = botão Sim e Não

        if (dialogButton == JOptionPane.YES_OPTION) {
            Limpar();
            DefaultTableModel tabelaProdutos = (DefaultTableModel) tblProdutos.getModel();
            tabelaProdutos.setNumRows(0);
        }

    }//GEN-LAST:event_btnClearActionPerformed

    private void btnEntradaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEntradaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEntradaMouseClicked

    private void btnProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProdutoActionPerformed
        // TODO add your handling code here:
        new FormProduto().setVisible(true);
    }//GEN-LAST:event_btnProdutoActionPerformed

    private void cbProdutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbProdutoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cbProdutoMouseClicked

    private void btnProdutoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnProdutoFocusLost
        // TODO add your handling code here:
        cbProduto.removeAllItems();

        ProdutoDAO prodDAO = new ProdutoDAO();
        ArrayList<Produto> prod = new ArrayList<Produto>();
        prod = prodDAO.getProdutosByDesc();

        for (Produto p : prod) {
            if (p != null) {
                cbProduto.addItem(p.getDescProduto());
            }
        }
        cbProduto.setSelectedIndex(-1);
    }//GEN-LAST:event_btnProdutoFocusLost

    private void rbEntradaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbEntradaMouseClicked
        // TODO add your handling code here:
        if (rbEntrada.isSelected()) 
        {   
            btnEntrada.setEnabled(true);
            btnSaida.setEnabled(false);       
            btnConcluir.setEnabled(true);
            btnClear.setEnabled(true);
            lblFornecedor.setVisible(true);
            btnFornecedor.setVisible(true);
            cbFornecedor.setVisible(true);
        }

    }//GEN-LAST:event_rbEntradaMouseClicked

    private void rbSaidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbSaidaMouseClicked
        // TODO add your handling code here:
        if (rbSaida.isSelected()) 
        {  
            preencheTabela();
            
            btnConcluir.setEnabled(true);
            btnClear.setEnabled(false);
            lblFornecedor.setVisible(true);
            btnFornecedor.setVisible(true);
            cbFornecedor.setVisible(true);
        }
    }//GEN-LAST:event_rbSaidaMouseClicked

    private void btnFornecedorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnFornecedorFocusLost
        // TODO add your handling code here:
        cbFornecedor.removeAllItems();

        PessoaDAO fornDAO = new PessoaDAO();
            ArrayList<Pessoa> forn = new ArrayList<Pessoa>();
            forn = fornDAO.getFornecedor();

        for (Pessoa f : forn) {
            if (f != null) {
                cbFornecedor.addItem(f.getP_nome());
            }
        }
        cbFornecedor.setSelectedIndex(-1);
    }//GEN-LAST:event_btnFornecedorFocusLost

    private void btnFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFornecedorActionPerformed
        // TODO add your handling code here:
        new FormFornecedor().setVisible(true);
    }//GEN-LAST:event_btnFornecedorActionPerformed

    private void btnConcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConcluirActionPerformed
        // TODO add your handling code here:            
        DefaultTableModel tabelaProdutos = (DefaultTableModel) tblProdutos.getModel();
        Pedido ped = new Pedido();

        DecimalFormat df = new DecimalFormat("R$ "+"#,###,##0.00");

        if (cbFuncionario.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(null, "Selecione um funcionario !", "ATENÇÃO", JOptionPane.INFORMATION_MESSAGE);
        }

        if (tabelaProdutos.getRowCount() == 0) {
            JOptionPane.showMessageDialog(null, "É necessário adicionar algum produto !", "ATENÇÃO", JOptionPane.INFORMATION_MESSAGE);
        }

        if (cbFornecedor.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(null, "Selecione um fornecedor !", "ATENÇÃO", JOptionPane.INFORMATION_MESSAGE);
        }

        if (tabelaProdutos.getRowCount() != 0)// && cbCliente.getSelectedIndex() != -1)
        {
            try 
            {     
                for (int x = 0; x < tblProdutos.getRowCount(); x++) 
                {
                    int ped_Cod = Integer.parseInt(tblProdutos.getValueAt(x, 0).toString());
                    ped.setPed_cod(ped_Cod);
                    
                    String ped_Data = lblData.getText();
                    ped.setPed_data(ped_Data);
                    //ped.setPed_data(ConverteData.converteData(ped_Data));
                    
                    String ped_Tipo = String.valueOf(tblProdutos.getValueAt(x, 2).toString());
                    ped.setPed_tipo(ped_Tipo);
                    
                    int pes_Id = cbFuncionario.getSelectedIndex();  
                    ped.setPes_id(pes_Id);
                    //int pes_Id = Integer.parseInt(tblProdutos.getValueAt(x, 3).toString());
                    //ped.setPes_id(pes_Id);
                    txtDestino.setText(String.valueOf(pes_Id));
                    String ped_Destino = String.valueOf(tblProdutos.getValueAt(x, 4).toString());
                    ped.setPed_destino(ped_Destino);
                    /*
                    int item_Cod = Integer.parseInt(tblProdutos.getValueAt(x, 5).toString());
                    ped.setItem_cod(item_Cod);
                    
                    //int prod_Cod = Integer.valueOf(tblProdutos.getValueAt(x, 6).toString());
                    int item_prod_Cod = cbProduto.getSelectedIndex();  
                    ped.setProd_cod(item_prod_Cod);
                    
                    int item_Qtde = Integer.parseInt(tblProdutos.getValueAt(x, 7).toString());
                    ped.setItem_qtde(item_Qtde);
                    
                    float item_Valor = Float.parseFloat(tblProdutos.getValueAt(x, 8).toString().replace(".", "").replace(",", "."));
                    ped.setItem_valor(item_Valor);
                    
                    int item_ped_Cod = Integer.parseInt(tblProdutos.getValueAt(x, 5).toString());
                    ped.setPed_cod(item_ped_Cod);
                    */                                   
                                                            
                    if (this.pedidoDAO.inserir(ped) == true) {
                        JOptionPane.showMessageDialog(null, "Pedido do(a) cliente [ " + cbFornecedor.getSelectedItem() + " ] inserido com sucesso ! \n\n"
                                + "-", "ATENÇÃO", JOptionPane.INFORMATION_MESSAGE);
                    } else {
                        JOptionPane.showMessageDialog(null, "Não foi possível salvar este pedido !", "ATENÇÃO", JOptionPane.ERROR_MESSAGE);
                    }
                }
                Limpar();

            } catch (NumberFormatException | HeadlessException e) {
                JOptionPane.showMessageDialog(null, "Não foi possível salvar este pedido \n\n Contate o Administrador do Sistema ! !\nErro: " + e.getMessage(), "ATENÇÃO", JOptionPane.ERROR_MESSAGE);
                System.out.println(e.getMessage());
                Limpar();
            }
        }
    }//GEN-LAST:event_btnConcluirActionPerformed

    private void tblProdutosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProdutosMouseClicked
        // TODO add your handling code here:
        popularComboFuncionario();
        //cbTipo.updateUI();
        
        int linhaselecionada = tblProdutos.getSelectedRow(); //pega a linha selecionada
        
        txtItem.setText(tblProdutos.getValueAt(linhaselecionada, 0).toString());
        cbProduto.setSelectedItem(tblProdutos.getValueAt(linhaselecionada, 1).toString());
        txtQtde.setText(tblProdutos.getValueAt(linhaselecionada, 2).toString());
        txtValor.setText(tblProdutos.getValueAt(linhaselecionada, 3).toString().replace(".", "").replace(",", "."));
        txtDestino.setText(tblProdutos.getValueAt(linhaselecionada, 4).toString());
        cbFuncionario.setSelectedItem(tblProdutos.getValueAt(linhaselecionada, 3));
    }//GEN-LAST:event_tblProdutosMouseClicked

    private void btnFuncionarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnFuncionarioFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFuncionarioFocusLost

    private void btnFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFuncionarioActionPerformed
        // TODO add your handling code here:
        new FormFuncionario().setVisible(true);
    }//GEN-LAST:event_btnFuncionarioActionPerformed

    private void txtItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormEstoque().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnConcluir;
    private javax.swing.JButton btnEntrada;
    private javax.swing.JButton btnFornecedor;
    private javax.swing.JButton btnFuncionario;
    private javax.swing.JButton btnProduto;
    private javax.swing.JButton btnSaida;
    private javax.swing.JComboBox cbFornecedor;
    private javax.swing.JComboBox cbFuncionario;
    private javax.swing.JComboBox cbProduto;
    private javax.swing.ButtonGroup grupoEstoque;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblData;
    private javax.swing.JLabel lblDestino;
    private javax.swing.JLabel lblFornecedor;
    private javax.swing.JLabel lblFuncionario;
    private javax.swing.JLabel lblHora;
    private javax.swing.JLabel lblProduto;
    private javax.swing.JLabel lblQtde;
    private javax.swing.JLabel lblSituacao;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblValor;
    private javax.swing.JPanel pnlEstoque;
    private javax.swing.JPanel pnlProduto;
    private javax.swing.JRadioButton rbEntrada;
    private javax.swing.JRadioButton rbSaida;
    private javax.swing.JTable tblProdutos;
    private javax.swing.JTextField txtDestino;
    private javax.swing.JTextField txtItem;
    private javax.swing.JTextField txtQtde;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables

    class hora implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent e) {
            Calendar now = Calendar.getInstance();
            lblHora.setText(String.format("%1$tH:%1$tM:%1$tS", now));
        }
    }
    
    //metodo para popular combo tipo
    public void popularComboFuncionario() {
                
        PessoaDAO pDAO = new PessoaDAO();
        ArrayList<Pessoa> listFunc = pDAO.getFuncionario();
        if (listFunc.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Cadastre pelo menos um funcionário !");
            this.dispose();
        } else {
            for(Pessoa func : listFunc){
                cbFuncionario.addItem(func);
            }
        }
    }
    
    public void Limpar() {
        cbFuncionario.setSelectedIndex(-1);
        txtItem.setText("");
        cbProduto.setSelectedIndex(-1);
        txtQtde.setText("");
        txtValor.setText("");

        cbFornecedor.setSelectedIndex(-1);
        DefaultTableModel tabelaProdutos = (DefaultTableModel) tblProdutos.getModel();
        tabelaProdutos.setNumRows(0);
        txtItem.setText("1");
    }
    
    public void somarColunaTotal()  
    {
        DecimalFormat df = new DecimalFormat("R$ "+"#,###,##0.00");
        
        int linhaselecionada = tblProdutos.getSelectedRow(); //pega a linha selecionada
                        
        DefaultTableModel modelo = (DefaultTableModel)tblProdutos.getModel();    
        double soma = 0;
                
        for (int i=0; i<tblProdutos.getRowCount(); i++)   
        {     
            double valor = Double.parseDouble(String.valueOf(modelo.getValueAt(i,8)));//pega a coluna Valor Total     
            soma += valor;    
        }    
        
        String novoValor = String.valueOf(df.format(soma));  
        txtTotal.setText(novoValor.replace(".","").replace(".", ","));
    }
    
    private void preencheTabela()
     {
        DefaultTableCellRenderer esquerda = new DefaultTableCellRenderer();
        DefaultTableCellRenderer centralizado = new DefaultTableCellRenderer();
        DefaultTableCellRenderer direita = new DefaultTableCellRenderer();
            esquerda.setHorizontalAlignment(SwingConstants.LEFT);
            centralizado.setHorizontalAlignment(SwingConstants.CENTER);
            direita.setHorizontalAlignment(SwingConstants.RIGHT);
            
        tblProdutos.getColumnModel().getColumn(0).setCellRenderer(centralizado);
        tblProdutos.getColumnModel().getColumn(1).setCellRenderer(esquerda);
        tblProdutos.getColumnModel().getColumn(2).setCellRenderer(centralizado);
        tblProdutos.getColumnModel().getColumn(3).setCellRenderer(centralizado);
        tblProdutos.getColumnModel().getColumn(4).setCellRenderer(esquerda);
         
        tblProdutos.getColumnModel().getColumn(0).setPreferredWidth(15);    //codigo
        tblProdutos.getColumnModel().getColumn(1).setPreferredWidth(45);    //data
        tblProdutos.getColumnModel().getColumn(2).setPreferredWidth(5);     //tipo
        tblProdutos.getColumnModel().getColumn(3).setPreferredWidth(35);    //funcionario
        tblProdutos.getColumnModel().getColumn(4).setPreferredWidth(100);   //destino
         
        ArrayList<Pedido> pedido = new ArrayList<Pedido>();
        pedido = this.pedidoDAO.getPedidoByTipo();
        
        DefaultTableModel tabela = (DefaultTableModel)tblProdutos.getModel();
        tabela.setNumRows(0);
        
        for (Pedido ped : pedido) 
        {
            if (ped != null) 
            {
                Object[] obj = new Object[]{
                    ped.getPed_cod(),
                    ped.getPed_data(),
                    ped.getPed_tipo(),
                    ped.getPes_id(),
                    ped.getPed_destino()
                };
                tabela.addRow(obj);
            }
        }        
    }
}
