/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package View;

import Model.Pedido;
import Model.Pessoa;
import Model.Produto;
import Controller.PedidoDAO;
import Controller.PessoaDAO;
import Controller.ProdutoDAO;
import java.awt.HeadlessException;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import utilitarios.AceitaNumeros;
import utilitarios.AceitaNumerosPonto;
import utilitarios.ConverteData;

/**
 *
 * @author Strong
 */
public class FormVenda extends javax.swing.JFrame {

    private PedidoDAO pedidoDAO;
    /**
     * Creates new form caixa
     */
    double valorRecebido = 0;
    double total = 0;
    
    public FormVenda() {
        initComponents();
        txtItem.setVisible(false);
        lblSituacao.setVisible(false);
        
        txtQtde.setDocument(new AceitaNumeros());
        txtValor.setDocument(new AceitaNumerosPonto());
        txtVRecebido.setDocument(new AceitaNumerosPonto());
        txtItem.setText(String.valueOf(tblProdutos.getRowCount()+1));
        
        this.pedidoDAO = new PedidoDAO();
        
        txtVRecebido.setText("0");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoPgto = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        lblFuncionario = new javax.swing.JLabel();
        pnlProd = new javax.swing.JPanel();
        lblProduto = new javax.swing.JLabel();
        cbProduto = new javax.swing.JComboBox();
        lblQtde = new javax.swing.JLabel();
        txtQtde = new javax.swing.JTextField();
        lblValor = new javax.swing.JLabel();
        txtValor = new javax.swing.JTextField();
        btnProd = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        lblTPagar = new javax.swing.JLabel();
        txtTroco = new javax.swing.JTextField();
        lblVRecebido = new javax.swing.JLabel();
        txtVRecebido = new javax.swing.JTextField();
        lblTroco = new javax.swing.JLabel();
        txtTPagar = new javax.swing.JTextField();
        pnlPgto = new javax.swing.JPanel();
        rbAVista = new javax.swing.JRadioButton();
        rbFiado = new javax.swing.JRadioButton();
        lblCliente = new javax.swing.JLabel();
        cbCliente = new javax.swing.JComboBox();
        btnCliente = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnRemove = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        txtItem = new javax.swing.JTextField();
        cbFuncionario = new javax.swing.JComboBox();
        btnConcluir = new javax.swing.JButton();
        lblSituacao = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProdutos = new javax.swing.JTable();
        lblData = new javax.swing.JLabel();
        lblHora = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(".: Controle Caixa :.");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblFuncionario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblFuncionario.setText("Funcionário:");

        pnlProd.setBorder(javax.swing.BorderFactory.createTitledBorder("Produtos:"));

        lblProduto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblProduto.setText("Produto:");

        cbProduto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbProdutoMouseClicked(evt);
            }
        });

        lblQtde.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblQtde.setText("Qtde:");

        txtQtde.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lblValor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblValor.setText("Valor Unitário:");

        txtValor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtValor.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        btnProd.setText("...");
        btnProd.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                btnProdFocusLost(evt);
            }
        });
        btnProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlProdLayout = new javax.swing.GroupLayout(pnlProd);
        pnlProd.setLayout(pnlProdLayout);
        pnlProdLayout.setHorizontalGroup(
            pnlProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProdLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlProdLayout.createSequentialGroup()
                        .addComponent(txtQtde, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addComponent(txtValor))
                    .addGroup(pnlProdLayout.createSequentialGroup()
                        .addGroup(pnlProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlProdLayout.createSequentialGroup()
                                .addComponent(lblProduto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnProd, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlProdLayout.createSequentialGroup()
                                .addComponent(lblQtde)
                                .addGap(96, 96, 96)
                                .addComponent(lblValor)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlProdLayout.setVerticalGroup(
            pnlProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProdLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProduto)
                    .addComponent(cbProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnProd))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQtde)
                    .addComponent(lblValor))
                .addGap(7, 7, 7)
                .addGroup(pnlProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtQtde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblTPagar.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblTPagar.setText("Total à Pagar");

        txtTroco.setEditable(false);
        txtTroco.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtTroco.setForeground(new java.awt.Color(255, 255, 255));
        txtTroco.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtTroco.setText("0");
        txtTroco.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        txtTroco.setEnabled(false);
        txtTroco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTrocoActionPerformed(evt);
            }
        });
        txtTroco.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtTrocoFocusGained(evt);
            }
        });

        lblVRecebido.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblVRecebido.setText("Valor Recebido");

        txtVRecebido.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtVRecebido.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtVRecebido.setText("0");
        txtVRecebido.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtVRecebidoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtVRecebidoFocusLost(evt);
            }
        });

        lblTroco.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblTroco.setText("Troco");

        txtTPagar.setEditable(false);
        txtTPagar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtTPagar.setForeground(new java.awt.Color(255, 255, 255));
        txtTPagar.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtTPagar.setText("0");
        txtTPagar.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        txtTPagar.setEnabled(false);

        pnlPgto.setBorder(javax.swing.BorderFactory.createTitledBorder("Pagamento:"));

        rbAVista.setText("à Vista");
        rbAVista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbAVistaMouseClicked(evt);
            }
        });

        rbFiado.setText("Fiado");
        rbFiado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbFiadoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlPgtoLayout = new javax.swing.GroupLayout(pnlPgto);
        pnlPgto.setLayout(pnlPgtoLayout);
        pnlPgtoLayout.setHorizontalGroup(
            pnlPgtoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPgtoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rbAVista)
                .addGap(18, 18, 18)
                .addComponent(rbFiado)
                .addGap(15, 15, 15))
        );
        pnlPgtoLayout.setVerticalGroup(
            pnlPgtoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPgtoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(rbAVista)
                .addComponent(rbFiado))
        );

        lblCliente.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblCliente.setText("Cliente:");

        cbCliente.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        btnCliente.setText("...");
        btnCliente.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                btnClienteFocusLost(evt);
            }
        });
        btnCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTroco, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblVRecebido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtVRecebido, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblTPagar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtTroco, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbCliente, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(7, 7, 7)
                        .addComponent(btnCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(52, 52, 52))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(lblCliente))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(pnlPgto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlPgto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCliente))
                .addGap(18, 18, 18)
                .addComponent(lblTPagar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTPagar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblVRecebido)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtVRecebido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTroco)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTroco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Add.png"))); // NOI18N
        btnAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddMouseClicked(evt);
            }
        });
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnRemove.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/remove.png"))); // NOI18N
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });

        btnClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Clear.png"))); // NOI18N
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        txtItem.setEditable(false);
        txtItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtItemActionPerformed(evt);
            }
        });

        btnConcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ok.png"))); // NOI18N
        btnConcluir.setText("Concluir");
        btnConcluir.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnConcluir.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnConcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConcluirActionPerformed(evt);
            }
        });

        lblSituacao.setText("Em Aberto");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlProd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnConcluir)
                        .addGap(18, 18, 18)
                        .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFuncionario)
                            .addComponent(txtItem, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSituacao)
                            .addComponent(cbFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFuncionario)
                    .addComponent(cbFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSituacao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnConcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66))
        );

        pnlProd.getAccessibleContext().setAccessibleDescription("");

        tblProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item", "Descrição", "Qtde", "Valor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblProdutos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProdutosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblProdutos);
        if (tblProdutos.getColumnModel().getColumnCount() > 0) {
            tblProdutos.getColumnModel().getColumn(0).setResizable(false);
            tblProdutos.getColumnModel().getColumn(1).setResizable(false);
            tblProdutos.getColumnModel().getColumn(2).setResizable(false);
            tblProdutos.getColumnModel().getColumn(3).setResizable(false);
        }

        lblData.setForeground(new java.awt.Color(0, 0, 204));
        lblData.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblData.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Calendar.png"))); // NOI18N
        lblData.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblData.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        lblHora.setFont(new java.awt.Font("Impact", 0, 16)); // NOI18N
        lblHora.setForeground(new java.awt.Color(0, 0, 204));
        lblHora.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblHora.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/clock.png"))); // NOI18N
        lblHora.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblData, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 275, Short.MAX_VALUE)
                        .addComponent(lblHora, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 641, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblHora, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
                               
        //Pega Data
        Date dataSistema = new Date();
        
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        //EEEE - mostra o dia da semana por extenso
        lblData.setText(formato.format(dataSistema));
        
        //Pega Hora
        Timer timer = new Timer(1000, new hora());
        timer.start();
                
        PessoaDAO pes = new PessoaDAO(); 
        Pessoa[] funcionario = pes.getFunc();
        
        for (int i = 0; i < funcionario.length; i++)
        {
            if (funcionario[i] != null)
            {
                cbFuncionario.addItem(funcionario[i].getP_nome());
            }
        }
        cbFuncionario.setSelectedIndex(-1);
                
        ProdutoDAO prodDAO = new ProdutoDAO();
        ArrayList<Produto> prod = new ArrayList<Produto>();
        prod = prodDAO.getProdutosByDesc();
        
        for (Produto p : prod) 
        {
            if (p != null)
            {
                cbProduto.addItem(p.getDescProduto());
            }
        }
                
        btnConcluir.setEnabled(true);
        grupoPgto.add(rbAVista);
        grupoPgto.add(rbFiado);
        rbAVista.setSelected(true);// inicia selecionado
        
        cbProduto.setSelectedIndex(-1);
        lblCliente.setVisible(false);
        btnCliente.setVisible(false);
        cbCliente.setVisible(false);
        //Pega Hora
        /*Timer timer = new Timer(1000, new hora());
        timer.start();*/
    }//GEN-LAST:event_formWindowOpened

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        try
        {
        String item = txtItem.getText();
        String produto = cbProduto.getSelectedItem().toString();
        String qtde = txtQtde.getText();
        String valor = txtValor.getText();
             
        double valorItem = 0;
        
        DecimalFormat df = new DecimalFormat("#,###.00");
        valorItem = Double.parseDouble(qtde) * Double.parseDouble(valor);
        
        DefaultTableModel tabelaProdutos = (DefaultTableModel)tblProdutos.getModel();
        Object[] obj = new Object[]{
            item,
            produto,
            qtde,
            //valorItem
            df.format(valorItem)
        };
        total = (Double.parseDouble(txtTPagar.getText().replace(".","").replace(",", ".")) + valorItem); // . = , e , = .
        
        
        //df.format(total);
        //txtTPagar.setText(String.valueOf(total));
        txtTPagar.setText(df.format(total));
        tabelaProdutos.addRow(obj);
        txtItem.setText(String.valueOf(tblProdutos.getRowCount()+1));
        cbProduto.setSelectedItem(-1);
        txtQtde.setText("");
        txtValor.setText("");
        txtQtde.requestFocus();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "É necessário preencher corretamente todos\n os campos do Produto !\nErro: " + e.getMessage());
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        // TODO add your handling code here:
        int linhaSelecionada = tblProdutos.getSelectedRow();
        DecimalFormat df = new DecimalFormat("#,###.00");
        
        if (linhaSelecionada >= 0)
        {
            DefaultTableModel tabelaProdutos = (DefaultTableModel)tblProdutos.getModel();
            tabelaProdutos.removeRow(linhaSelecionada);
            
            total = (Double.parseDouble(txtTPagar.getText().replace(".","").replace(",", ".")) - Double.parseDouble(txtValor.getText()));
            txtTPagar.setText(df.format(total));
            
            cbProduto.setSelectedIndex(-1);
            txtQtde.setText("");
            txtValor.setText("");
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Selecione um produto para remover da lista !");
        }
    }//GEN-LAST:event_btnRemoveActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        int dialogButton = JOptionPane.showConfirmDialog (null, "Tem certeza que deseja limpar todos os campos ?","Warning",0);// 0 = botão Sim e Não

       if (dialogButton == JOptionPane.YES_OPTION)
       {
            Limpar();
            DefaultTableModel tabelaProdutos = (DefaultTableModel)tblProdutos.getModel();
            tabelaProdutos.setNumRows(0);
       }
       
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddMouseClicked

    private void txtVRecebidoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtVRecebidoFocusLost
        // TODO add your handling code here:
        try
        {
            valorRecebido = 0;
            String recebido = txtVRecebido.getText();
            String pagar = txtTPagar.getText().replace(".","").replace(",", ".");
            
            DecimalFormat df = new DecimalFormat("#,###.00");
            
            valorRecebido = Double.parseDouble(txtVRecebido.getText()) - Double.parseDouble(txtTPagar.getText().replace(".","").replace(",", "."));
            txtTroco.setText(df.format(valorRecebido));        
            
            
            if (Double.parseDouble(recebido) < Double.parseDouble(pagar))
            {
                txtTroco.setText("0");
                JOptionPane.showMessageDialog(null, "O valor recebido é inferior ao Total do Pedido !");
                txtVRecebido.requestFocus();
            }
            else if (tblProdutos.getRowCount() != 0 && txtVRecebido.getText() != "0")
            {
                JOptionPane.showMessageDialog(null, "Não se esqueça de clicar em Concluir\n para salvar o pedido !!!","ATENÇÃO",JOptionPane.INFORMATION_MESSAGE);
                //Limpar();
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "Valor Recebido não pode ser vazio !\nErro: " + e.getMessage(),"ATENÇÃO",JOptionPane.ERROR_MESSAGE);
            txtVRecebido.requestFocus();
        }
    }//GEN-LAST:event_txtVRecebidoFocusLost

    private void txtItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtItemActionPerformed

    private void txtTrocoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTrocoFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTrocoFocusGained

    private void btnProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProdActionPerformed
        // TODO add your handling code here:
        new FormProduto().setVisible(true);
    }//GEN-LAST:event_btnProdActionPerformed

    private void cbProdutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbProdutoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cbProdutoMouseClicked

    private void btnProdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnProdFocusLost
        // TODO add your handling code here:
        cbProduto.removeAllItems();
        
        ProdutoDAO prodDAO = new ProdutoDAO();
        ArrayList<Produto> prod = new ArrayList<Produto>();
        prod = prodDAO.getProdutosByDesc();
        
        for (Produto p : prod) 
        {
            if (p != null)
            {
                cbProduto.addItem(p.getDescProduto());
            }
        }
        cbProduto.setSelectedIndex(-1);
    }//GEN-LAST:event_btnProdFocusLost

    private void rbAVistaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbAVistaMouseClicked
        // TODO add your handling code here:
        if (rbAVista.isSelected())
        {
           cbCliente.removeAllItems();
           
           btnConcluir.setEnabled(true);
           btnClear.setEnabled(true);
           lblCliente.setVisible(false);
           btnCliente.setVisible(false);
           cbCliente.setVisible(false);
           lblVRecebido.setVisible(true);
           txtVRecebido.setVisible(true);
           lblTroco.setVisible(true);
           txtTroco.setVisible(true);
        }
       
    }//GEN-LAST:event_rbAVistaMouseClicked

    private void rbFiadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbFiadoMouseClicked
        // TODO add your handling code here:
        if (rbFiado.isSelected())
        {
            
        PessoaDAO cliDAO = new PessoaDAO();
        ArrayList<Pessoa> cli = new ArrayList<Pessoa>();
        cli = cliDAO.getCliente();
                    
        for (Pessoa c : cli) 
        {
            if (c != null)
            {
                cbCliente.addItem(c.getP_nome());
            }
        }
        cbCliente.setSelectedIndex(-1);
        
            btnConcluir.setEnabled(true);
            btnClear.setEnabled(false);
            lblCliente.setVisible(true);
            btnCliente.setVisible(true);
            cbCliente.setVisible(true);
            lblVRecebido.setVisible(false);
            txtVRecebido.setVisible(false);
            lblTroco.setVisible(false);
            txtTroco.setVisible(false);
        }
    }//GEN-LAST:event_rbFiadoMouseClicked

    private void txtTrocoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTrocoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTrocoActionPerformed

    private void btnClienteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnClienteFocusLost
        // TODO add your handling code here:
        cbCliente.removeAllItems();
                
        PessoaDAO cliDAO = new PessoaDAO();
        ArrayList<Pessoa> cli = new ArrayList<Pessoa>();
        cli = cliDAO.getCliente();
                    
        for (Pessoa c : cli) 
        {
            if (c != null)
            {
                cbCliente.addItem(c.getP_nome());
            }
        }
        cbCliente.setSelectedIndex(-1);
    }//GEN-LAST:event_btnClienteFocusLost

    private void btnClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClienteActionPerformed
        // TODO add your handling code here:
        new FormPessoa().setVisible(true);
    }//GEN-LAST:event_btnClienteActionPerformed

    private void txtVRecebidoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtVRecebidoFocusGained
        // TODO add your handling code here:
        //txtVRecebido.setText("");
    }//GEN-LAST:event_txtVRecebidoFocusGained

    private void btnConcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConcluirActionPerformed
        // TODO add your handling code here:            
        DefaultTableModel tabelaProdutos = (DefaultTableModel)tblProdutos.getModel();
        Pedido ped = new Pedido();    
        DecimalFormat df = new DecimalFormat("#,###.00");
        
        if (cbFuncionario.getSelectedIndex() == -1)
        {
            JOptionPane.showMessageDialog(null, "Selecione um funcionario !","ATENÇÃO",JOptionPane.INFORMATION_MESSAGE);
        }
        
        if (tabelaProdutos.getRowCount() == 0)
        {
           JOptionPane.showMessageDialog(null, "É necessário adicionar algum produto !","ATENÇÃO",JOptionPane.INFORMATION_MESSAGE); 
        }
                      
        if (rbFiado.isSelected() && cbCliente.getSelectedIndex() == -1)
        {
            JOptionPane.showMessageDialog(null, "Selecione um cliente !","ATENÇÃO",JOptionPane.INFORMATION_MESSAGE);
        }
                        
        if (tabelaProdutos.getRowCount() != 0)// && cbCliente.getSelectedIndex() != -1)
        {
            try
            {     
                 if (txtVRecebido.getText().equals("0") && rbAVista.isSelected())
                {
                    JOptionPane.showMessageDialog(null, "Informe o Valor Recebido !","ATENÇÃO",JOptionPane.INFORMATION_MESSAGE);
                    txtVRecebido.requestFocus();
                }
                else
                {
                    for(int x = 0; x < tblProdutos.getRowCount();x++)
                    {              
                        int ped_Item = Integer.parseInt(tblProdutos.getValueAt(x, 0).toString());  
                        ped.setPedItem(ped_Item);
                    
                        String ped_Produto = String.valueOf(tblProdutos.getValueAt(x, 1).toString());                   
                        ped.setPedProduto(ped_Produto);
                    
                        int ped_Qtde = Integer.parseInt(tblProdutos.getValueAt(x, 2).toString());  
                        ped.setPedQtde(ped_Qtde);
                    
                        float ped_Vtotal = Float.parseFloat(tblProdutos.getValueAt(x, 3).toString().replace(".","").replace(",", "."));  
                        ped.setPedVtotal(ped_Vtotal);
                    
                        String ped_Cliente = "";
                    
                        if (rbAVista.isSelected())
                        {
                            String ped_Pgto = "à Vista";  
                            ped.setPedPgto(ped_Pgto);
                        }
                        else if (rbFiado.isSelected())
                        {
                            String ped_Pgto = "Fiado";  
                            ped.setPedPgto(ped_Pgto);
                            ped_Cliente = cbCliente.getSelectedItem().toString();
                            ped.setPedCliente(ped_Cliente);
                        }                    
                    
                        String ped_Data = lblData.getText();
                        ped.setPedData(ConverteData.converteData(ped_Data));
                    
                        if (rbAVista.isSelected())
                        {
                            String ped_Situacao = "P A G O";
                            ped.setPedSituacao(ped_Situacao);
                        }
                        else if (rbFiado.isSelected())
                        {
                            String ped_Situacao = "Em Aberto";
                            ped.setPedSituacao(ped_Situacao);
                        }
                    
                        String ped_Func = cbFuncionario.getSelectedItem().toString();  
                        ped.setPedFunc(ped_Func);
                    
                        if(this.pedidoDAO.inserir(ped) == true)
                        {
                            JOptionPane.showMessageDialog(null, "Pedido do(a) cliente [ "+cbCliente.getSelectedItem()+" ] inserido com sucesso ! \n\n"
                                    + "Obrigado e Volte Sempre !!","ATENÇÃO",JOptionPane.INFORMATION_MESSAGE);                    
                        }
                        else
                        {
                            JOptionPane.showMessageDialog(null, "Não foi possível salvar este pedido !","ATENÇÃO",JOptionPane.ERROR_MESSAGE);
                        }
                    }
                    Limpar();
                 }
            }
            catch(NumberFormatException | HeadlessException e)
            {
                JOptionPane.showMessageDialog(null, "Não foi possível salvar este pedido \n\n Contate o Administrador do Sistema ! !\nErro: " + e.getMessage(),"ATENÇÃO",JOptionPane.ERROR_MESSAGE);
                System.out.println(e.getMessage());
                Limpar();
            }
        }
    }//GEN-LAST:event_btnConcluirActionPerformed

    private void tblProdutosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProdutosMouseClicked
        // TODO add your handling code here:
        int linhaselecionada = tblProdutos.getSelectedRow(); //pega a linha selecionada
        txtItem.setText(tblProdutos.getValueAt(linhaselecionada, 0).toString());
        cbProduto.setSelectedItem(tblProdutos.getValueAt(linhaselecionada, 1).toString());
        txtQtde.setText(tblProdutos.getValueAt(linhaselecionada, 2).toString());
        txtValor.setText(tblProdutos.getValueAt(linhaselecionada, 3).toString().replace(".", "").replace(",", "."));
    }//GEN-LAST:event_tblProdutosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormVenda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnCliente;
    private javax.swing.JButton btnConcluir;
    private javax.swing.JButton btnProd;
    private javax.swing.JButton btnRemove;
    private javax.swing.JComboBox cbCliente;
    private javax.swing.JComboBox cbFuncionario;
    private javax.swing.JComboBox cbProduto;
    private javax.swing.ButtonGroup grupoPgto;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCliente;
    private javax.swing.JLabel lblData;
    private javax.swing.JLabel lblFuncionario;
    private javax.swing.JLabel lblHora;
    private javax.swing.JLabel lblProduto;
    private javax.swing.JLabel lblQtde;
    private javax.swing.JLabel lblSituacao;
    private javax.swing.JLabel lblTPagar;
    private javax.swing.JLabel lblTroco;
    private javax.swing.JLabel lblVRecebido;
    private javax.swing.JLabel lblValor;
    private javax.swing.JPanel pnlPgto;
    private javax.swing.JPanel pnlProd;
    private javax.swing.JRadioButton rbAVista;
    private javax.swing.JRadioButton rbFiado;
    private javax.swing.JTable tblProdutos;
    private javax.swing.JTextField txtItem;
    private javax.swing.JTextField txtQtde;
    private javax.swing.JTextField txtTPagar;
    private javax.swing.JTextField txtTroco;
    private javax.swing.JTextField txtVRecebido;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables

    class hora implements ActionListener
    {
        @Override
        public void actionPerformed(ActionEvent e)
        {
            Calendar now = Calendar.getInstance();
            lblHora.setText(String.format("%1$tH:%1$tM:%1$tS", now));
        }
    }
    
    public void Limpar()
    {
        cbFuncionario.setSelectedIndex(-1);
        txtItem.setText("");
        cbProduto.setSelectedIndex(-1);
        txtQtde.setText("");
        txtValor.setText("");
        txtTPagar.setText("0");
        txtVRecebido.setText("0");
        txtTroco.setText("0");
        cbCliente.setSelectedIndex(-1);
        DefaultTableModel tabelaProdutos = (DefaultTableModel)tblProdutos.getModel();
        tabelaProdutos.setNumRows(0);
        txtItem.setText("1");
    }
}
